owner: intellekthq
repo: statuspage

sites:
  - name: bustdown API
    url: https://bustdownapi.intellekt.fyi/api/health
    icon: https://raw.githubusercontent.com/intellekthq/statuspage/main/assets/bustdown.png
    expectedStatusCodes: [200]
    method: GET
  - name: kmap API
    url: https://kmap.api.intellekt.fyi/api/health
    icon: https://raw.githubusercontent.com/intellekthq/statuspage/main/assets/kmap.png
    expectedStatusCodes: [200]
    method: GET

status-website:
  cname: status.intellekt.fyi
  name: Intellekt Status
  logoUrl: https://raw.githubusercontent.com/intellekthq/statuspage/main/assets/logo.svg
  favicon: https://raw.githubusercontent.com/intellekthq/statuspage/main/assets/favicon.svg
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/intellekthq/statuspage

assignees:
  - mach-kernel

notifications: []
